// Code generated by modgadget-fonts. DO NOT EDIT.

package shinonome12

import fontpkg "github.com/rdon-key/modgadget-fonts/font"

var Font = fontpkg.New(
	fontpkg.Metrics{
		Ascent:  10,
		Descent: 2,
		LineGap: 0,
	},
	[]fontpkg.GlyphInfo{
		{
			Rune:         '\u65e5',
			BitmapOffset: 0,
			Width:        12,
			Height:       12,
			AdvanceX:     12,
			BearingX:     0,
			BearingY:     10,
		},
		{
			Rune:         '\u672c',
			BitmapOffset: 24,
			Width:        12,
			Height:       12,
			AdvanceX:     12,
			BearingX:     0,
			BearingY:     10,
		},
		{
			Rune:         '\u793a',
			BitmapOffset: 48,
			Width:        12,
			Height:       12,
			AdvanceX:     12,
			BearingX:     0,
			BearingY:     10,
		},
		{
			Rune:         '\u8868',
			BitmapOffset: 72,
			Width:        12,
			Height:       12,
			AdvanceX:     12,
			BearingX:     0,
			BearingY:     10,
		},
		{
			Rune:         '\u8a9e',
			BitmapOffset: 96,
			Width:        12,
			Height:       12,
			AdvanceX:     12,
			BearingX:     0,
			BearingY:     10,
		},
	},
	"\x00\x00?\x80 \x80 \x80 \x80 \x80?\x80 \x80 \x80 \x80 \x80?\x80\x04\x00\x04\x00\x04\x00\xff\xe0"+
		"\x0e\x00\x0e\x00\x15\x00$\x80_@\x84 \x04\x00\x04\x00\x00\x00?\x80\x00\x00\x00\x00\xff\xe0\x04\x00$\x80$@"+
		"D \x84 \x04\x00\f\x00\x04\x00\x7f\xc0\x04\x00\x7f\xc0\x04\x00\xff\xe0\x14\x802\x80\xd3\x00\x11\x00\x1c\x80p`"+
		"p\x00\x0f\xc0\xf2\x00\x0f\x80t\x80\x04\x80\x7f\xe0\x00\x00\xf7\xc0\x94@\x94@\xf7\xc0",
)
